# Generated by Django 6.0.2 on 2026-02-22 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('farmer_type', models.CharField(choices=[('Individual', 'Individual'), ('SHG', 'Self Help Group'), ('Cooperative', 'Cooperative')], max_length=20)),
                ('years_experience', models.PositiveIntegerField()),
                ('farm_address', models.TextField()),
                ('village', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('id_proof_type', models.CharField(max_length=50)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='farmer_certificates/')),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
