# Generated by Django 6.0.2 on 2026-05-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_address_label_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Farm', 'Farm'), ('Parents', 'Parents'), ('Other', 'Other')], default='Home', max_length=20),
        ),
    ]
